### ISSUE TITLE
找不到主机“cs-wiki.org”

### ISSUE THREAD

**Issue by Rratic** [cs-wiki-org/cs-wiki#1]
尝试ping，找不到主机
建议先把东西准备好再展示出来……（否则被抢注了就……）
话说这仓库还是空的……

**Comment by Menci** [comment]
![image](https://user-images.githubusercontent.com/11341955/115882713-9b67b900-a47f-11eb-84c2-71400375411a.png)

实际上创建 org 的同时我就已经注册了

**Comment by Rratic** [comment]
emmm

**Comment by Menci** [comment]
打算用 oi-wiki 新版框架来做
https://github.com/OI-wiki/gatsby-oi-wiki
